### ISSUE TITLE
🛑 Melody is Down

### ISSUE THREAD

**Issue by CodedJimmy** [TrizaCorporation/Status#340]
Melody is currently offline due to issues with discord's API.

**Comment by CodedJimmy** [comment]
**Information:** We're sorry about this outage, Discord's API is currently rate-limiting us from connecting to the gateway.

**Comment by CodedJimmy** [comment]
**Resolved:** We've resolved this issue.

**Comment by DaRealRomz** [comment]
We are glad to inform you that Melody is back online!
